### ISSUE TITLE
unknown symbols in project.janet

### ISSUE THREAD

**Issue by strangepete** [CFiggers/janet-lsp#28]
Hi, when editing a project.janet I get "unknown symbol" errors for any of the `;default-` flags, like `;default-cflags`, `-lflags`, etc,  as well as the macros `(sh-task)` & `(sh-phony)`. I see this error in various projects that incorporate these elements. Tried reinstalling, but same. Not sure if it matters, but only first `;default-` found will show an error, the rest are not marked until placed first. Despite any of the above errors, the project will compile/install just fine.

Adding task/phony was an easy fix, but I'm not sure where to look for the `;default-` parts. Anything I can do to help diagnose?

VSC 1.95.3
Janet++ 1.1.6
Windows 10
Janet 1.35.2

Edit: somehow I missed the other repository, **vscode-janet-plus-plus**...sorry if this is in the wrong place

**Comment by CFiggers** [comment]
This is the right place. :)

In order to make Janet LSP play nicely with JPM symbols, there is a file in `libs/` that defines them. They're then imported as part of the LSP server's startup (in `src/main.janet` somewhere). I wasn't aware of the `default-*` and `sh-*` symbols. But it's pretty easy to add them. Just need to expand `libs/jpm-defs.janet`.

Is this the complete list of the ones that are giving you problems?

- default-cflags
- default-lflags
- default-ldflags
- default-cppflags
- sh-task
- sh-phony

**Comment by strangepete** [comment]
I poked around a few of the top official janet repositories and I came across jaylib & circlet using plain ol' `(phony)` as well. Otherwise, those are the only ones I've noticed so far.

I successfully added the prototypes for sh-task & sh-phony,  but I'm not sure where to put the default- stuff...I see all the cflags etc defined in (declare-executable), but I'm using it in (declare-native) that only takes 'opts', a couple things i've tried haven't worked

**Comment by strangepete** [comment]
Ok this seems to work just fine, I added the other missing macros, and set the defs to a empty []. I was definitely overthinking things as usual :) Thanks
